"""create department table

Revision ID: 0d051708c4e3
Revises: 8601d08be82b
Create Date: 2025-11-17 18:31:35.883033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d051708c4e3'
down_revision: Union[str, Sequence[str], None] = '8601d08be82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.add_column('employees', sa.Column('address', sa.String(length=100), nullable=False))
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('employees', 'address')
    op.drop_table('department')
    # ### end Alembic commands ###
